apiVersion: v1
kind: Service
metadata:
  name: cadence-liquidsoap
  labels:
    app: cadence-liquidsoap
spec:
  type: ClusterIP
  ports:
  - port: 1234
    targetPort: 1234
    protocol: TCP
  selector:
    app: cadence-liquidsoap
