apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cadence-example

commonLabels:
  app: cadence

resources:
- ./namespace.yaml
- ./configmap.yaml
- ./ingress.yaml
- ./persistentVolume.yaml
- ./persistentVolumeClaim.yaml
- ./storageClass.yaml

bases:
- ../../base
