apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cadence

resources:
- ./namespace.yaml
- ./configmap.yaml
- ./ingress.yaml
- ./persistentVolumeClaim.yaml

bases:
- ../../base
